FROM golang:1.23-alpine AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -tags netgo -ldflags '-w -s' -o /out/protoc-gen-go-template .

FROM gcr.io/distroless/static:nonroot
COPY --from=builder /out/protoc-gen-go-template /protoc-gen-go-template
USER nonroot
ENTRYPOINT ["/protoc-gen-go-template"]
