name: buf-publish

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push plugin
        env:
          BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
        run: |
          buf alpha plugin push \
            --visibility public \
            --image-file Dockerfile.buf
